# Generated by Django 4.2.3 on 2023-07-19 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0004_alter_goal_options_remove_goal_is_deleted_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='goal',
            old_name='update',
            new_name='updated',
        ),
        migrations.RenameField(
            model_name='goalcategory',
            old_name='update',
            new_name='updated',
        ),
        migrations.RenameField(
            model_name='goalcomment',
            old_name='update',
            new_name='updated',
        ),
    ]
